version: '3.8'

services:
  app:
    container_name: management-system
    image: node:18-alpine
    restart: always
    working_dir: /app/management
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app/management
      - ./algorithm/utils/nomask_people:/data/management/nomask_people
      - ./algorithm/runs/detect:/data/management/detect
    ports:
      - '3002:3002'
    command: "npm start"

  mongo:
    container_name: management-mongo
    image: mongo:4.4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: m4a1421

  proxy:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    privileged: true
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=192.168.137.248
      - NGINX_PORT=80
